config/routes.rb
FlatRent::Application.routes.draw do
  resources :photos

  resources :offers

  resources :events do
    collection do
         get :likeit
     end
  end

  authenticated do
    root :to => 'home#index', as: :authenticated
  end
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  mount Commontator::Engine => '/commontator'
end

app/models/offer.rb
class Offer < ActiveRecord::Base
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:title, :cost, :picture, :start_date, :end_date, :area, :rooms, :localization, :description)
    end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<div class="authform">
<%= simple_form_for(@offer) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.label :title %>
     <%= f.text_field :title, :autofocus => true, class: 'form-control' %>
    </div>
    <div class="form-group">
    <%= f.label :cost %>
    <%= f.text_field :cost, :autofocus => true, class: 'form-control' %>
    </div>
    <div class="form-group">
    <%= f.input :start_date, :autofocus => true, class: 'form-control' %>
    </div>
    <div class="form-group">
    <%= f.input :end_date, :autofocus => true, class: 'form-control' %>
    </div>
    <div class="form-group">
    <%= f.label :area %>
     <%= f.text_field :area, :autofocus => true, class: 'form-control' %>
    </div>
    <div class="form-group">
    <%= f.input :rooms, :autofocus => true, class: 'form-control' %>
    </div>
    <div class="form-group">
    <%= f.label :localization %>
     <%= f.text_field :localization, :autofocus => true, class: 'form-control' %>
    </div>
    <div class="form-group">
    <%= f.input :description, :autofocus => true, class: 'form-control' %>
  </div>
       
 

  <div class="form-actions">
    <%= f.submit 'Submit', :class => 'button right' %>
  </div>
<% end %>
</div>

app/views/offers/edit.html.erb
<div class='head'>
<h1>Editing offer</h1>
</div>

<%= render 'form' %>

<%= link_to "<button>Show</button>".html_safe, @offer, :id=>"open-contacts-dialog-btn", :class=>"inbox-sf-add-btn tip" %>
<%= link_to "<button>Back</button>".html_safe, offers_path, :id=>"open-contacts-dialog-btn", :class=>"inbox-sf-add-btn tip" %>

app/views/offers/index.html.erb
<div class='head'>
<h1>Listing offers</h1>
</div>


<div class='tabele'>
<table>
  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.picture %></td>
        <td><p id='t'><%= offer.title %></p>
        <p id='data'><%= offer.start_date %>
        <%= offer.end_date %>
        <%= offer.localization %></p>
        <p id='g'><%= offer.description %></p>
        <div id='button-list'>
          <%= link_to "<button>Show</button>".html_safe, offer, :id=>"open-contacts-dialog-btn", :class=>"inbox-sf-add-btn tip" %>
          <%= link_to "<button>Edit</button>".html_safe, edit_offer_path(offer), :id=>"open-contacts-dialog-btn", :class=>"inbox-sf-add-btn tip" %>
          <%= link_to "<button>Destroy</button>".html_safe,  offer, :id=>"open-contacts-dialog-btn", :class=>"inbox-sf-add-btn tip", method: :delete, data: { confirm: 'Are you sure?' } %>
       </div>
       </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>
<%= link_to "<button>New Offer</button>".html_safe, new_offer_path, :id=>"open-contacts-dialog-btn", :class=>"inbox-sf-add-btn tip" %>

app/views/offers/new.html.erb
<div class='head'>
<h1>New offer</h1>
</div>
<%= render 'form' %>

<%= link_to "<button>Back</button>".html_safe, offers_path, :id=>"open-contacts-dialog-btn", :class=>"inbox-sf-add-btn tip" %>

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<div class='event_view'>

<div class='head'>
  <strong><%= @offer.title %></strong>
</div>
<div id='txt'>
<p>
  <strong>Cost:</strong>
  <%= @offer.cost %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @offer.picture %>
</p>

<%= image_tag('/images/icotime.png') %>
<p id='picture'>
  <strong>Start date:</strong>
  <%= @offer.start_date %>

</p>

<p>
  <strong>End date:</strong>
  <%= @offer.end_date %>
</p>

<p>
  <strong>Area:</strong>
  <%= @offer.area %>
</p>

<p>
  <strong>Rooms:</strong>
  <%= @offer.rooms %>
</p>

<%= image_tag('/images/icoplace.png') %>
<p id='picture'>
  <strong>Localization:</strong>
  <%= @offer.localization %>
  
</p>
</div>
<div id='descript'> 
<p>
  <strong>Description:</strong>
  <%= @offer.description %>
</p>
</div>
<%= link_to "<button>Edit</button>".html_safe,  edit_offer_path(@offer), :id=>"open-contacts-dialog-btn", :class=>"inbox-sf-add-btn tip" %>
   <%= link_to "<button>Back</button>".html_safe,  offers_path, :id=>"open-contacts-dialog-btn", :class=>"inbox-sf-add-btn tip" %>
</div>